apiVersion: v1
kind: Service
metadata:
  name: k8s-cert-exporter
  labels:
    app: k8s-cert-exporter
spec:
  ports:
  - port: 8000
    name: web
  clusterIP: None
  selector:
    app: k8s-cert-exporter
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k8s-cert-exporter
spec:
  selector:
    matchLabels:
      app: k8s-cert-exporter # has to match .spec.template.metadata.labels
  serviceName: k8s-cert-exporter
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: k8s-cert-exporter # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: docker-registry:5000/prometheus-python-cert-exporter:latest
        volumeMounts:
          - mountPath: /etc/kubernetes/pki/
            name: certs-folder
        ports:
        - containerPort: 8000
          name: web
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: "Exists"
        effect: NoSchedule
      volumes:
      - name: certs-folder
        hostPath:
          path: /etc/kubernetes/pki/
          type: DirectoryOrCreate
